language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements/dev.txt
env:
  global:
    - DEBUG=True
    - DJANGO_SETTINGS_MODULE=ideax.settings.test
    - SECRET_KEY=12345678901234567890123456789012345678901234567890
    - GENERAL_USER_GROUP=General
    - ALLOWED_HOSTS=.localhost,ideax
# command to run tests
script:
  - flake8 ideax
  - py.test
