# Generated by Django 2.0.9 on 2018-12-06 12:39

from django.db import migrations, models
import ideax.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.PositiveSmallIntegerField(choices=[(ideax.users.models.AuthType((1, 'LDAP')), (1, 'LDAP')), (ideax.users.models.AuthType((2, 'AD')), (2, 'AD'))])),
                ('host', models.CharField(max_length=50)),
                ('bind_dn', models.CharField(max_length=100)),
                ('bind_password', models.CharField(max_length=40)),
                ('user_search_base', models.CharField(max_length=120)),
                ('user_filter', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
