# Generated by Django 2.0.9 on 2019-01-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_type', models.PositiveSmallIntegerField(choices=[(1, 'LDAP')])),
                ('host', models.CharField(max_length=50)),
                ('bind_dn', models.CharField(max_length=100)),
                ('bind_password', models.CharField(max_length=40)),
                ('user_search_base', models.CharField(max_length=120)),
                ('user_filter', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('configuration_date', models.DateTimeField(null=True)),
                ('configuration_admin_ip', models.CharField(max_length=20, null=True)),
                ('configuration_admin', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
