# Generated by Django 2.0.9 on 2018-12-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0024_auto_20181023_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveSmallIntegerField(default=False)),
            ],
            options={
                'verbose_name': 'Idea Phase',
            },
        ),
        migrations.AlterField(
            model_name='phase_history',
            name='current_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_phase', to='ideax.IdeaPhase'),
        ),
    ]
