# Generated by Django 2.0.9 on 2018-11-08 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0024_auto_20181023_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0)),
        ),
    ]
