# Generated by Django 2.0.9 on 2019-01-24 14:05

from django.db import migrations, models
import ideax.tenant.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0026_auto_20181206_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_image',
            name='image',
            field=models.ImageField(storage=ideax.tenant.storage.TenantFileSystemStorageIdeax(), upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='image',
            field=models.ImageField(storage=ideax.tenant.storage.TenantFileSystemStorageIdeax(), upload_to='challenges/'),
        ),
    ]
